### ISSUE TITLE
[Fix✨] Ratings Issues

### ISSUE THREAD

**Issue by NLaw5** [Eventhood/Eventhood-app#85]
## Description
Multiline Issue:
- Whenever ratings ended up being more than two decimal places, this ended up being a multiline issue, as the ratings appeared to clip through the bubble in the user profile 

Shape Issue:
- Remove Oval bubble to allow for more space to include an indicator for rating next to number (for instance, adding a star next to the number)

Word Clarity:
- On the rating list screen, for each user rating, word fix rate to **rating**

Multiple Ratings:
- Only allow a user to rate another user once

## Acceptance Criteria
All issues listed in description are resolved and allow for functionality to continue working.

## Testing
Ratings should still work with the new implementations from the fix indicated in description

**Comment by Kevan-Y** [comment]
The rating can be added once fixed by https://github.com/Eventhood/Eventhood-app/commit/2d40a96d421643a3a3a21444bc21c34d03be2d18
