### ISSUE TITLE
[Fix✨] Hosts Events Issue

### ISSUE THREAD

**Issue by NLaw5** [Eventhood/Eventhood-app#86]
## Description
On user profile, if User has 0 events, it should display as **0** instead of N/A.

## Acceptance Criteria
If user has 0 hosted events, the display should show as **0** when issue is fixed.

## Testing
Users that have 0 host events will display 0 instead of N/A on their user profile.

**Comment by Kevan-Y** [comment]
Fixed by https://github.com/Eventhood/Eventhood-app/commit/6cf3551a836244f9621ecbd4dd1a1f70f08d966d
