### ISSUE TITLE
[Fix✨] Form Submission Issues [Login/ Registration/ Create Event/ Edit Event]

### ISSUE THREAD

**Issue by NLaw5** [Eventhood/Eventhood-app#87]
## Description
Form submission buttons for Login/Registration/Create Event/Edit Event need the following changes when action is performed:
- Disable button
- Display message/symbol to indicate to user that the action they want is currently being processed (ex. Registering a User, creating an event, etc.)

This issue is primarily so that Users are notified that the action they have performed is being processed, and that the button being disabled will not allow users to spam the action button during the action performance.

## Acceptance Criteria
When a user performs an action for form submission, the button should be disabled and some sort of symbol or message indicating that the action is being performed is shown to the user.

## Testing
Users should be able to have the inability to spam the action button to submit a form, while being notified that the action is currently being performed.

**Comment by Kevan-Y** [comment]
Fixed by https://github.com/Eventhood/Eventhood-app/commit/6c29f2f1d3b28a222641a3942129e9149fe42168 and https://github.com/Eventhood/Eventhood-app/commit/4dc57cbb7286293152faba79e2936581de78ee02
