### ISSUE TITLE
[Fix✨] Edit Event Issues 

### ISSUE THREAD

**Issue by NLaw5** [Eventhood/Eventhood-app#89]
## Description
Any incorrectly edited event should have an error message associated so users can know what was incorrect in the edited fields when submitting an edit.

Any empty fields or incorrect fields should not allow for events to be edited, returning an error message to the user.

## Acceptance Criteria
Edit Event screen should display the appropriate messages if form for edit submission is incorrect, and will not allow for the event to be updated or saved in the database.

## Testing
Incorrect edit information for an event does not allow for the event to be saved, and system will indicate with error messages as to which fields are incorrectly filled or empty for event edit.

**Comment by Kevan-Y** [comment]
Fixed by https://github.com/Eventhood/Eventhood-app/commit/6c29f2f1d3b28a222641a3942129e9149fe42168
