### ISSUE TITLE
[Fix✨] Event Delete Alert Box Issue 

### ISSUE THREAD

**Issue by NLaw5** [Eventhood/Eventhood-app#92]
## Description
When an event is deleted, two alert boxes must be created:

1.  Confirm intent to delete for user
2.  If confirmation of intent to delete is true, indicate to user that the event has been deleted

## Acceptance Criteria
As a user, I should be able to see alert boxes indicating a confirmation delete. If confirmation is true, user should be able to see another alert box load in and indicate that the event is confirmed to be deleted.

## Testing
System should only return one alert box indicating confirmation of delete, if confirmation of delete is false.

System should return two alert boxes if confirmation of delete in the first alert box is true, in which the second alert box will be loaded in confirming that the event has been deleted.

**Comment by Kevan-Y** [comment]
Fixed by https://github.com/Eventhood/Eventhood-app/commit/6c29f2f1d3b28a222641a3942129e9149fe42168
